#!/bin/bash

#######################################################################
# Documentation of problem.
#
# This is a reconnection problem from Bill Daughton which has a grid
# size of 256x128x128 and can be weak scaled in the y-direction. The
# grid dimensions only contain factors of 2 which limits its utility
# for testing on Trinity KNL and CTS1 Broadwell nodes at LANL. This
# version of the problem allows for extensive file IO.
#
#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   0000001  # MPI Domain Grid: 256 x 128 x 128
make_input_deck_template  1*2   1*1   1*1   0000002  # MPI Domain Grid: 128 x 128 x 128
make_input_deck_template  1*2   1*2   1*1   0000004  # MPI Domain Grid: 128 x  64 x 128
make_input_deck_template  1*2   1*2   1*2   0000008  # MPI Domain Grid: 128 x  64 x  64
make_input_deck_template  1*4   1*2   1*2   0000016  # MPI Domain Grid:  64 x  64 x  64
make_input_deck_template  1*4   1*4   1*2   0000032  # MPI Domain Grid:  64 x  32 x  64
make_input_deck_template  1*8   1*4   1*2   0000064  # MPI Domain Grid:  32 x  32 x  64
make_input_deck_template  1*8   1*8   1*2   0000128  # MPI Domain Grid:  32 x  16 x  64
make_input_deck_template  1*16  1*8   1*2   0000256  # MPI Domain Grid:  16 x  16 x  64
make_input_deck_template  2*16  1*8   1*2   0000512  # MPI Domain Grid:   8 x  16 x  64
make_input_deck_template  2*16  2*8   1*2   0001024  # MPI Domain Grid:   8 x   8 x  64
make_input_deck_template  4*16  2*8   1*2   0002048  # MPI Domain Grid:   4 x   8 x  64
