#!/bin/bash

aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,32-47,16-31,48-63 reconnection_hbm_nn_0001_nppn_002.Linux --tpp  64 >& run_reconnection_hbm_nn_0001_nppn_002_064.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,16-31             reconnection_hbm_nn_0001_nppn_002.Linux --tpp  32 >& run_reconnection_hbm_nn_0001_nppn_002_032.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7,16-23              reconnection_hbm_nn_0001_nppn_002.Linux --tpp  16 >& run_reconnection_hbm_nn_0001_nppn_002_016.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3,16-19              reconnection_hbm_nn_0001_nppn_002.Linux --tpp   8 >& run_reconnection_hbm_nn_0001_nppn_002_008.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1,16-17              reconnection_hbm_nn_0001_nppn_002.Linux --tpp   4 >& run_reconnection_hbm_nn_0001_nppn_002_004.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0,16                   reconnection_hbm_nn_0001_nppn_002.Linux --tpp   2 >& run_reconnection_hbm_nn_0001_nppn_002_002.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0                      reconnection_hbm_nn_0001_nppn_001.Linux --tpp   1 >& run_reconnection_hbm_nn_0001_nppn_001_001.log

aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,32-47,16-31,48-63 reconnection_nn_0001_nppn_002.Linux --tpp  64 >& run_reconnection_nn_0001_nppn_002_064.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,16-31             reconnection_nn_0001_nppn_002.Linux --tpp  32 >& run_reconnection_nn_0001_nppn_002_032.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7,16-23              reconnection_nn_0001_nppn_002.Linux --tpp  16 >& run_reconnection_nn_0001_nppn_002_016.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3,16-19              reconnection_nn_0001_nppn_002.Linux --tpp   8 >& run_reconnection_nn_0001_nppn_002_008.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1,16-17              reconnection_nn_0001_nppn_002.Linux --tpp   4 >& run_reconnection_nn_0001_nppn_002_004.log
aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0,16                   reconnection_nn_0001_nppn_002.Linux --tpp   2 >& run_reconnection_nn_0001_nppn_002_002.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0                      reconnection_nn_0001_nppn_001.Linux --tpp   1 >& run_reconnection_nn_0001_nppn_001_001.log
