#!/bin/bash

aprun -n 64 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_064.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_064_004.log
aprun -n 32 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_032.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_032_004.log
aprun -n 16 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_016.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_016_004.log
aprun -n  8 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_008.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_008_004.log
aprun -n  4 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_004.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_004_004.log
aprun -n  2 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_002.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_002_004.log
aprun -n  1 -d 4 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_001.Linux --tpp 4 >& run_reconnection_nn_0001_nppn_001_004.log

aprun -n 64 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_064.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_064_003.log
aprun -n 32 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_032.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_032_003.log
aprun -n 16 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_016.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_016_003.log
aprun -n  8 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_008.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_008_003.log
aprun -n  4 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_004.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_004_003.log
aprun -n  2 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_002.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_002_003.log
aprun -n  1 -d 3 -j 3 /usr/bin/time -p reconnection_nn_0001_nppn_001.Linux --tpp 3 >& run_reconnection_nn_0001_nppn_001_003.log

aprun -n 64 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_064.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_064_002.log
aprun -n 32 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_032.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_032_002.log
aprun -n 16 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_016.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_016_002.log
aprun -n  8 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_008.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_008_002.log
aprun -n  4 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_004.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_004_002.log
aprun -n  2 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_002.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_002_002.log
aprun -n  1 -d 2 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_001.Linux --tpp 2 >& run_reconnection_nn_0001_nppn_001_002.log
