#!/bin/bash

export LD_LIBRARY_PATH=/usr/gapps/artab/users/wdn/Projects/vpic_project/build/RZUSEQ_MASTER_LINUX_GNU_OPT_IBM_MPI_V4_PORT/vpic/lib/.libs:$LD_LIBRARY_PATH

/usr/bin/time -p srun -n 64 --ntasks-per-node=64 --ntasks-per-socket=64 --ntasks-per-core=4 --overcommit test_Seq_case_02_np_64.powerpc64 >& run_test_Seq_case_02_np_64.log
