#!/bin/bash

export LD_LIBRARY_PATH=/home/wdn/Projects/vpic_project/build/KITTEN_MASTER_LINUX_GNU_OPT_OPENMPI_V4_PORT/vpic/lib/.libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/wdn/Packages/OpenMPI/openmpi_1.8.1_gcc_482/lib:$LD_LIBRARY_PATH

/usr/bin/time -p /home/wdn/Packages/OpenMPI/openmpi_1.8.1_gcc_482/bin/mpirun -n 16 -npersocket 8 test_Seq_case_02_np_16.x86_64 --tpp 2 >& run_test_Seq_case_02_np_16_2.log
