#!/bin/bash

#######################################################################
# Documentation of problem.
#
# This set of input files is designed to allow for strong scaling
# studies of an LPI problem on Trinity Haswell, Trinity KNL and CTS1
# Broadwell nodes.  As a consequence, the grid dimensions has factors
# of 2, 17 and two factors of 3. This particular setup allows for a
# strong scaling study up to 8 nodes.
#
#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   00001  # MPI Domain Grid: 544 x 96 x 96
make_input_deck_template  1*2   1*1   1*1   00002  # MPI Domain Grid: 272 x 96 x 96
make_input_deck_template  1*2   1*2   1*1   00004  # MPI Domain Grid: 272 x 48 x 96
make_input_deck_template  1*2   1*2   1*2   00008  # MPI Domain Grid: 272 x 48 x 48
make_input_deck_template  1*4   1*2   1*2   00016  # MPI Domain Grid: 136 x 48 x 48
make_input_deck_template  1*17  1*1   1*1   00017  # MPI Domain Grid:  32 x 96 x 96
make_input_deck_template  1*4   1*4   1*2   00032  # MPI Domain Grid: 136 x 24 x 48
make_input_deck_template  1*17  1*2   1*1   00034  # MPI Domain Grid:  32 x 48 x 96
make_input_deck_template  1*4   1*4   1*4   00064  # MPI Domain Grid: 136 x 24 x 24
make_input_deck_template  1*17  1*2   1*2   00068  # MPI Domain Grid:  32 x 48 x 48
make_input_deck_template  1*8   1*4   1*4   00128  # MPI Domain Grid:  68 x 24 x 24
make_input_deck_template  1*17  1*4   1*2   00136  # MPI Domain Grid:  32 x 24 x 48

make_input_deck_template  1*16  1*4   1*4   00256  # MPI Domain Grid:  34 x 24 x 24
make_input_deck_template  2*16  1*4   1*4   00512  # MPI Domain Grid:  17 x 24 x 24
make_input_deck_template  2*16  2*4   1*4   01024  # MPI Domain Grid:  17 x 12 x 24
make_input_deck_template  2*16  2*4   2*4   02048  # MPI Domain Grid:  17 x 12 x 12

make_input_deck_template  1*17  1*4   1*4   00272  # MPI Domain Grid:  32 x 24 x 24
make_input_deck_template  2*17  1*4   1*4   00544  # MPI Domain Grid:  16 x 24 x 24
make_input_deck_template  2*17  2*4   1*4   01088  # MPI Domain Grid:  16 x 12 x 24
make_input_deck_template  2*17  2*4   2*4   02176  # MPI Domain Grid:  16 x 12 x 12

make_input_deck_template  1*2   1*3   1*1   00006  # MPI Domain Grid: 272 x 32 x 96
make_input_deck_template  1*4   1*3   1*1   00012  # MPI Domain Grid: 136 x 32 x 96
make_input_deck_template  1*2   1*3   1*3   00018  # MPI Domain Grid: 272 x 32 x 32
make_input_deck_template  1*8   1*3   1*1   00024  # MPI Domain Grid:  68 x 32 x 96
make_input_deck_template  1*4   1*3   1*3   00036  # MPI Domain Grid: 136 x 32 x 32
make_input_deck_template  1*8   1*3   1*2   00048  # MPI Domain Grid:  68 x 32 x 48

make_input_deck_template  1*8   1*3   1*3   00072  # MPI Domain Grid:  68 x 32 x 32
make_input_deck_template  2*8   1*3   1*3   00144  # MPI Domain Grid:  34 x 32 x 32
make_input_deck_template  2*8   2*3   1*3   00288  # MPI Domain Grid:  34 x 16 x 32
make_input_deck_template  2*8   2*3   2*3   00576  # MPI Domain Grid:  34 x 16 x 16
