#!/bin/bash

export LD_LIBRARY_PATH=/usr/gapps/artab/users/wdn/Projects/vpic_project/build/RZUSEQ_MASTER_LINUX_GNU_OPT_IBM_MPI_V4_ALTIVEC/vpic/lib/.libs:$LD_LIBRARY_PATH

/usr/bin/time -p srun -n 8 --ntasks-per-node=8 --ntasks-per-socket=8 --ntasks-per-core=1 test_Seq_case_02_np_08.powerpc64 >& run_test_Seq_case_02_np_08.log
