#!/bin/bash
#PBS -j oe
#PBS -N vpic_knl_mpi_0512
#PBS -l walltime=2:00:00
#PBS -l nodes=512

#set -x

cd ${PBS_O_WORKDIR}

source ./bashrc.modules

module list

aprun -n 131072 -N 256 -d 1 -j 4 reconnection_nn_0512_nppn_256.Linux >& run_reconnection_nn_0512_nppn_256_001.log
