#!/bin/bash
#MSUB -l walltime=8:00:00
#MSUB -l nodes=2048:ppn=8
#MSUB -N asymmetric
#MSUB -j oe

module swap PrgEnv-intel PrgEnv-gnu

export HIO_data_roots=.

#export HIO_data_roots=DataWarp,posix:.
#export HIO_datawarp_root=/tmp/dw_vpic/users/wdn/fan_reconnection/case_nodes_2048

#export HIO_print_statistics=true

/usr/bin/time -p aprun -n 16384 -N 8 -S 4 -d 8 -j 2 turbulence_sheet_tracer_np_16384_08.op -tpp=8 restart restart1/restart >& run_turbulence_sheet_tracer_np_16384_08_restart.log
