#!/bin/bash

export PATH=/home/wdn/Packages/openmpi/openmpi_1.10.2_int_1700_beta_01/bin:$PATH

mpirun -n 1 -bind-to-core -bycore /usr/bin/time -p test_lpi_np_00001.Linux --tpp 2 >& run_test_lpi_np_00001_002.log
mpirun -n 2 -bind-to-core -bycore /usr/bin/time -p test_lpi_np_00002.Linux --tpp 2 >& run_test_lpi_np_00002_002.log
mpirun -n 4 -bind-to-core -bycore /usr/bin/time -p test_lpi_np_00004.Linux --tpp 2 >& run_test_lpi_np_00004_002.log
