#!/bin/bash
#MSUB -l walltime=8:00:00
#MSUB -l nodes=64:ppn=8
#MSUB -N asymmetric
#MSUB -j oe

#DW jobdw access_mode=striped type=scratch capacity=6TiB

module swap PrgEnv-intel PrgEnv-gnu

#aprun -n 1 mkdir -p /tmp/dw_vpic/users/wdn/fan_reconnection/case_nodes_0064

#export HIO_data_roots=.

export HIO_data_roots=DataWarp,posix:.
#export HIO_datawarp_root=/tmp/dw_vpic/users/wdn/fan_reconnection/case_nodes_0064

#export HIO_print_statistics=true

/usr/bin/time -p aprun -n 512 -N 8 -S 4 -d 8 -j 2 turbulence_sheet_tracer_np_00512_08.op -tpp=8 >& run_turbulence_sheet_tracer_np_00512_08.log
