#!/bin/bash

export LD_LIBRARY_PATH=/home/wdn/Packages/OpenMPI/openmpi_1.8.1_gcc_482/lib:$LD_LIBRARY_PATH

/usr/bin/time -p /home/wdn/Packages/OpenMPI/openmpi_1.8.1_gcc_482/bin/mpirun -n 1 test_Seq_case_02_np_01.op --tpp 1 >& run_test_Seq_case_02_np_01_1.log
