#!/bin/bash

source /opt/intel/bin/compilervars.sh intel64

export PATH=/home/wdn/Packages/openmpi/openmpi_1.10.2_int_1601/bin:$PATH

/usr/bin/time -p mpirun -n 4 test_Seq_case_02_np_04.Linux >& run_test_Seq_case_02_np_04_1.log
