#!/bin/bash

aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131,136-199,204-267 test_lpi_hbm_np_00001.Linux --tpp 256 >& run_test_lpi_hbm_np_00001_256.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131                 test_lpi_hbm_np_00001.Linux --tpp 128 >& run_test_lpi_hbm_np_00001_128.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63                        test_lpi_hbm_np_00001.Linux --tpp  64 >& run_test_lpi_hbm_np_00001_064.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-31                        test_lpi_hbm_np_00001.Linux --tpp  32 >& run_test_lpi_hbm_np_00001_032.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15                        test_lpi_hbm_np_00001.Linux --tpp  16 >& run_test_lpi_hbm_np_00001_016.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7                         test_lpi_hbm_np_00001.Linux --tpp   8 >& run_test_lpi_hbm_np_00001_008.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3                         test_lpi_hbm_np_00001.Linux --tpp   4 >& run_test_lpi_hbm_np_00001_004.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1                         test_lpi_hbm_np_00001.Linux --tpp   2 >& run_test_lpi_hbm_np_00001_002.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+1                           test_lpi_hbm_np_00001.Linux --tpp   1 >& run_test_lpi_hbm_np_00001_001.log

aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131,136-199,204-267 test_lpi_np_00001.Linux --tpp 256 >& run_test_lpi_np_00001_256.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131                 test_lpi_np_00001.Linux --tpp 128 >& run_test_lpi_np_00001_128.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63                        test_lpi_np_00001.Linux --tpp  64 >& run_test_lpi_np_00001_064.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-31                        test_lpi_np_00001.Linux --tpp  32 >& run_test_lpi_np_00001_032.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15                        test_lpi_np_00001.Linux --tpp  16 >& run_test_lpi_np_00001_016.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7                         test_lpi_np_00001.Linux --tpp   8 >& run_test_lpi_np_00001_008.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3                         test_lpi_np_00001.Linux --tpp   4 >& run_test_lpi_np_00001_004.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1                         test_lpi_np_00001.Linux --tpp   2 >& run_test_lpi_np_00001_002.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+1                           test_lpi_np_00001.Linux --tpp   1 >& run_test_lpi_np_00001_001.log
