#!/bin/bash
#PBS -j oe
#PBS -N vpic_knl_mpi_and_pthreads_0128
#PBS -l walltime=2:00:00
#PBS -l nodes=128

#set -x

cd ${PBS_O_WORKDIR}

source ./bashrc.modules

module list

aprun -n 8192 -N 64 -d 4 -j 4 reconnection_nn_0128_nppn_064.Linux --tpp 4 >& run_reconnection_nn_0128_nppn_064_004.log
