#!/bin/bash

#######################################################################
# Set run parameters.

nranks_x=$1
nranks_y=$2
nranks_z=$3
nranks=$4

#######################################################################
# Edit the input file to use our configurable input parameters.

update='
s/REPLACE_topology_x/'${nranks_x}'/
s/REPLACE_topology_y/'${nranks_y}'/
s/REPLACE_topology_z/'${nranks_z}'/
'

cat lpi.template.master.cxx | sed -e "$update" >& lpi_np_${nranks}.template.cxx
