#!/bin/bash

#######################################################################
# Documentation of problem.
#
# This set of input files is designed to allow for strong scaling
# studies of an LPI problem on Trinity Haswell, Trinity KNL and CTS1
# Broadwell nodes.  As a consequence, the grid dimensions has factors
# of 2, 17 and two factors of 3. This particular setup allows for a
# strong scaling study up to 8 nodes.
#
#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   0000001  # MPI Domain Grid: 544 x 96 x 96
make_input_deck_template  1*2   1*1   1*1   0000002  # MPI Domain Grid: 272 x 96 x 96
make_input_deck_template  1*4   1*1   1*1   0000004  # MPI Domain Grid: 136 x 96 x 96
make_input_deck_template  1*8   1*1   1*1   0000008  # MPI Domain Grid:  68 x 96 x 96
make_input_deck_template  1*16  1*1   1*1   0000016  # MPI Domain Grid:  34 x 96 x 96
make_input_deck_template  1*17  1*1   1*1   0000017  # MPI Domain Grid:  32 x 96 x 96
make_input_deck_template  1*16  1*2   1*1   0000032  # MPI Domain Grid:  34 x 48 x 96
make_input_deck_template  1*17  1*2   1*1   0000034  # MPI Domain Grid:  32 x 48 x 96
make_input_deck_template  1*16  1*2   1*2   0000064  # MPI Domain Grid:  34 x 48 x 48
make_input_deck_template  1*17  1*2   1*2   0000068  # MPI Domain Grid:  32 x 48 x 48
make_input_deck_template  1*16  1*4   1*2   0000128  # MPI Domain Grid:  34 x 24 x 48
make_input_deck_template  1*17  1*4   1*2   0000136  # MPI Domain Grid:  32 x 24 x 48
make_input_deck_template  1*16  1*4   1*4   0000256  # MPI Domain Grid:  34 x 24 x 24
make_input_deck_template  1*17  1*4   1*4   0000272  # MPI Domain Grid:  32 x 24 x 24

make_input_deck_template  2*16  1*4   1*4   0000512  # MPI Domain Grid:  17 x 24 x 24
make_input_deck_template  2*16  2*4   1*4   0001024  # MPI Domain Grid:  17 x 12 x 24
make_input_deck_template  2*16  2*4   2*4   0002048  # MPI Domain Grid:  17 x 12 x 12

make_input_deck_template  2*17  1*4   1*4   0000544  # MPI Domain Grid:  16 x 24 x 24
make_input_deck_template  2*17  2*4   1*4   0001088  # MPI Domain Grid:  16 x 12 x 24
make_input_deck_template  2*17  2*4   2*4   0002176  # MPI Domain Grid:  16 x 12 x 12

make_input_deck_template  1*1   1*3   1*2   0000006  # MPI Domain Grid: 544 x 32 x 48
make_input_deck_template  1*2   1*3   1*2   0000012  # MPI Domain Grid: 272 x 32 x 48
make_input_deck_template  1*2   1*3   1*3   0000018  # MPI Domain Grid: 272 x 32 x 32
make_input_deck_template  1*4   1*3   1*2   0000024  # MPI Domain Grid: 136 x 32 x 48
make_input_deck_template  1*4   1*3   1*3   0000036  # MPI Domain Grid: 136 x 32 x 32
make_input_deck_template  1*8   1*3   1*2   0000048  # MPI Domain Grid:  68 x 32 x 48
make_input_deck_template  1*8   1*3   1*3   0000072  # MPI Domain Grid:  68 x 32 x 32

make_input_deck_template  2*8   1*3   1*3   0000144  # MPI Domain Grid:  34 x 32 x 32
make_input_deck_template  2*8   2*3   1*3   0000288  # MPI Domain Grid:  34 x 16 x 32
make_input_deck_template  2*8   2*3   2*3   0000576  # MPI Domain Grid:  34 x 16 x 16
