#!/bin/bash

aprun -n  1 -S  1 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00001_001.log
aprun -n  2 -S  1 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00002_001.log
aprun -n  4 -S  2 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00004_001.log
aprun -n  8 -S  4 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00008_001.log
aprun -n 16 -S  8 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00016_001.log
aprun -n 32 -S 16 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00032_001.log
aprun -n 64 -S 32 -d 1 -j 2 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00064_001.log

#aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0                      test_lpi_np_00001.Linux --tpp   1 >& run_test_lpi_np_00001_001.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0,16                   test_lpi_np_00001.Linux --tpp   2 >& run_test_lpi_np_00001_002.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1,16-17              test_lpi_np_00001.Linux --tpp   4 >& run_test_lpi_np_00001_004.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3,16-19              test_lpi_np_00001.Linux --tpp   8 >& run_test_lpi_np_00001_008.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7,16-23              test_lpi_np_00001.Linux --tpp  16 >& run_test_lpi_np_00001_016.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,16-31             test_lpi_np_00001.Linux --tpp  32 >& run_test_lpi_np_00001_032.log
#aprun -n 2 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15,32-47,16-31,48-63 test_lpi_np_00001.Linux --tpp  64 >& run_test_lpi_np_00001_064.log
