#!/bin/tcsh
#MSUB -l walltime=48:00:00
#MSUB -l nodes=4096
#MSUB -N asymmetric
#MSUB -j oe

# Now run the script as this group - so all data files will belong

# Set number of times to restart the moving window

#  Shell commands
date
echo '*** Starting Parallel Job ***'
module switch PrgEnv-cray PrgEnv-gnu
cd /scratch1/users/daughton/Fan/
aprun -n 32768 -d 8 -j 2 ./turbulence-sheet-tracer.cxx.op -tpp=8 restart restart0/restart  >& output2
date
echo '*** All Done ***'

# 
