#!/bin/bash

export PATH=/home/wdn/Packages/openmpi/openmpi_1.10.1_gcc_511/bin:$PATH

#/usr/bin/time -p mpirun --use-hwthread-cpus --bind-to core --bycore -n 1 test_Seq_case_02_np_01.Linux --tpp 4 >& run_test_Seq_case_02_np_01_4.log

/usr/bin/time -p mpirun --bind-to none --byslot -n 1 test_Seq_case_02_np_01.Linux --tpp 4 >& run_test_Seq_case_02_np_01_4.log

#/usr/bin/time -p mpirun --bind-to none --report-bindings -n 1 test_Seq_case_02_np_01.Linux --tpp 4 >& run_test_Seq_case_02_np_01_4.log
