#!/bin/bash

aprun -n 2 -d  1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux --tpp  1 >& run_test_lpi_np_00002_001.log
aprun -n 2 -d  2 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux --tpp  2 >& run_test_lpi_np_00002_002.log
aprun -n 2 -d  4 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux --tpp  4 >& run_test_lpi_np_00002_004.log
aprun -n 2 -d  8 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux --tpp  8 >& run_test_lpi_np_00002_008.log
aprun -n 2 -d 16 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux --tpp 16 >& run_test_lpi_np_00002_016.log
aprun -n 2 -d 16 -j 2 /usr/bin/time -p test_lpi_np_00001.Linux --tpp 32 >& run_test_lpi_np_00002_032.log
