#!/bin/bash

export MPICH_MEMORY_REPORT=3

aprun -n 256 -d 1 -j 4 /usr/bin/time -p test_lpi_hbm_np_00256.Linux >& run_test_lpi_hbm_np_00256_001.log
aprun -n 128 -d 1 -j 2 /usr/bin/time -p test_lpi_hbm_np_00128.Linux >& run_test_lpi_hbm_np_00128_001.log
aprun -n  64 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00064.Linux >& run_test_lpi_hbm_np_00064_001.log
aprun -n  32 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00032.Linux >& run_test_lpi_hbm_np_00032_001.log
aprun -n  16 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00016.Linux >& run_test_lpi_hbm_np_00016_001.log
aprun -n   8 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00008.Linux >& run_test_lpi_hbm_np_00008_001.log
aprun -n   4 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00004.Linux >& run_test_lpi_hbm_np_00004_001.log
aprun -n   2 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00002.Linux >& run_test_lpi_hbm_np_00002_001.log
aprun -n   1 -d 1 -j 1 /usr/bin/time -p test_lpi_hbm_np_00001.Linux >& run_test_lpi_hbm_np_00001_001.log

aprun -n 256 -d 1 -j 4 /usr/bin/time -p test_lpi_np_00256.Linux >& run_test_lpi_np_00256_001.log
aprun -n 128 -d 1 -j 2 /usr/bin/time -p test_lpi_np_00128.Linux >& run_test_lpi_np_00128_001.log
aprun -n  64 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00064.Linux >& run_test_lpi_np_00064_001.log
aprun -n  32 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00032.Linux >& run_test_lpi_np_00032_001.log
aprun -n  16 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00016.Linux >& run_test_lpi_np_00016_001.log
aprun -n   8 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00008.Linux >& run_test_lpi_np_00008_001.log
aprun -n   4 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00004.Linux >& run_test_lpi_np_00004_001.log
aprun -n   2 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00002.Linux >& run_test_lpi_np_00002_001.log
aprun -n   1 -d 1 -j 1 /usr/bin/time -p test_lpi_np_00001.Linux >& run_test_lpi_np_00001_001.log
