#!/bin/bash

/usr/bin/time -p numactl --physcpubind=+1     test_lpi_np_00001.Linux --tpp   1 >& run_test_lpi_np_00001_001.log
/usr/bin/time -p numactl --physcpubind=+0-1   test_lpi_np_00001.Linux --tpp   2 >& run_test_lpi_np_00001_002.log
/usr/bin/time -p numactl --physcpubind=+0-3   test_lpi_np_00001.Linux --tpp   4 >& run_test_lpi_np_00001_004.log
/usr/bin/time -p numactl --physcpubind=+0-7   test_lpi_np_00001.Linux --tpp   8 >& run_test_lpi_np_00001_008.log
/usr/bin/time -p numactl --physcpubind=+0-15  test_lpi_np_00001.Linux --tpp  16 >& run_test_lpi_np_00001_016.log
/usr/bin/time -p numactl --physcpubind=+0-31  test_lpi_np_00001.Linux --tpp  32 >& run_test_lpi_np_00001_032.log
/usr/bin/time -p numactl --physcpubind=+0-63  test_lpi_np_00001.Linux --tpp  64 >& run_test_lpi_np_00001_064.log
/usr/bin/time -p numactl --physcpubind=+0-127 test_lpi_np_00001.Linux --tpp 128 >& run_test_lpi_np_00001_128.log
/usr/bin/time -p numactl --physcpubind=+0-255 test_lpi_np_00001.Linux --tpp 256 >& run_test_lpi_np_00001_256.log

/usr/bin/time -p numactl --physcpubind=+0-67  test_lpi_np_00001.Linux --tpp  68 >& run_test_lpi_np_00001_068.log
/usr/bin/time -p numactl --physcpubind=+0-135 test_lpi_np_00001.Linux --tpp 136 >& run_test_lpi_np_00001_136.log
/usr/bin/time -p numactl --physcpubind=+0-271 test_lpi_np_00001.Linux --tpp 272 >& run_test_lpi_np_00001_272.log
