#!/bin/bash
#PBS -j oe
#PBS -N vpic_knl_mpi_0004
#PBS -l walltime=2:00:00
#PBS -l nodes=4

#set -x

#cd ${PBS_O_WORKDIR}

source ./bashrc.modules

module list

export MPICH_MEMORY_REPORT=3

aprun -n 1024 -N 256 -d 1 -j 4 reconnection_nn_0004_nppn_256.Linux >& run_reconnection_nn_0004_nppn_256_001.log
