#!/bin/bash

#######################################################################
# Documentation of problem.
#
# This is a reconnection problem from Bill Daughton which has a grid
# size of 272x144x128 and can be weak scaled in the y-direction. The
# grid dimensions contain factors of 2, 3 and 17 and thus allow doing
# strong scaling studies on Trinity Haswell and KNL and CTS1 Broadwell
# and making comparisons across these three types of nodes. This input
# deck is related to reconnection_3 but allows writing extensive file
# IO.
#
#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   00001  # MPI Domain Grid: 272 x 144 x 128
make_input_deck_template  1*2   1*1   1*1   00002  # MPI Domain Grid: 136 x 144 x 128
make_input_deck_template  1*4   1*1   1*1   00004  # MPI Domain Grid:  68 x 144 x 128
make_input_deck_template  1*8   1*1   1*1   00008  # MPI Domain Grid:  34 x 144 x 128
make_input_deck_template  1*16  1*1   1*1   00016  # MPI Domain Grid:  17 x 144 x 128
make_input_deck_template  1*17  1*1   1*1   00017  # MPI Domain Grid:  16 x 144 x 128
make_input_deck_template  1*16  1*2   1*1   00032  # MPI Domain Grid:  17 x  72 x 128
make_input_deck_template  1*17  1*2   1*1   00034  # MPI Domain Grid:  16 x  72 x 128
make_input_deck_template  1*16  1*4   1*1   00064  # MPI Domain Grid:  17 x  36 x 128
make_input_deck_template  1*17  1*4   1*1   00068  # MPI Domain Grid:  16 x  36 x 128
make_input_deck_template  1*16  1*8   1*1   00128  # MPI Domain Grid:  17 x  18 x 128
make_input_deck_template  1*17  1*8   1*1   00136  # MPI Domain Grid:  16 x  18 x 128
make_input_deck_template  1*16  1*16  1*1   00256  # MPI Domain Grid:  17 x   9 x 128
make_input_deck_template  1*17  1*16  1*1   00272  # MPI Domain Grid:  16 x   9 x 128
make_input_deck_template  2*17  1*16  1*1   00544  # MPI Domain Grid:   8 x   9 x 128

make_input_deck_template  1*2   1*3   1*1   00006  # MPI Domain Grid: 136 x  48 x 128
make_input_deck_template  1*4   1*3   1*1   00012  # MPI Domain Grid:  68 x  48 x 128
make_input_deck_template  1*2   1*9   1*1   00018  # MPI Domain Grid: 136 x  16 x 128
make_input_deck_template  1*8   1*3   1*1   00024  # MPI Domain Grid:  34 x  48 x 128
make_input_deck_template  1*4   1*9   1*1   00036  # MPI Domain Grid:  68 x  16 x 128
make_input_deck_template  1*16  1*3   1*1   00048  # MPI Domain Grid:  17 x  48 x 128
make_input_deck_template  1*8   1*9   1*1   00072  # MPI Domain Grid:  34 x  16 x 128
make_input_deck_template  2*8   1*9   1*1   00144  # MPI Domain Grid:  17 x  16 x 128
make_input_deck_template  2*8   2*9   1*1   00288  # MPI Domain Grid:  17 x   8 x 128
