#!/bin/bash
#PBS -j oe
#PBS -N vpic_knl_mpi_and_pthreads_0064
#PBS -l walltime=2:00:00
#PBS -l nodes=64

#set -x

cd ${PBS_O_WORKDIR}

source ./bashrc.modules

module list

aprun -n 4096 -N 64 -d 4 -j 4 reconnection_nn_0064_nppn_064.Linux --tpp 4 >& run_reconnection_nn_0064_nppn_064_004.log
