#!/bin/bash

#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   00001
make_input_deck_template  1*2   1*1   1*1   00002
make_input_deck_template  1*2   1*2   1*1   00004
make_input_deck_template  1*2   1*2   1*2   00008
make_input_deck_template  1*4   1*2   1*2   00016
make_input_deck_template  1*17  1*1   1*1   00017
make_input_deck_template  1*4   1*4   1*2   00032
make_input_deck_template  1*17  1*2   1*1   00034
make_input_deck_template  1*4   1*4   1*4   00064
make_input_deck_template  1*17  1*2   1*2   00068
make_input_deck_template  1*8   1*4   1*4   00128
make_input_deck_template  1*17  1*4   1*2   00136

make_input_deck_template  1*16  1*4   1*4   00256
make_input_deck_template  2*16  1*4   1*4   00512
make_input_deck_template  2*16  2*4   1*4   01024
make_input_deck_template  2*16  2*4   2*4   02048

make_input_deck_template  1*17  1*4   1*4   00272
make_input_deck_template  2*17  1*4   1*4   00544
make_input_deck_template  2*17  2*4   1*4   01088
make_input_deck_template  2*17  2*4   2*4   02176

make_input_deck_template  1*2   1*3   1*1   00006
make_input_deck_template  1*4   1*3   1*1   00012
make_input_deck_template  1*2   1*3   1*3   00018
make_input_deck_template  1*8   1*3   1*1   00024
make_input_deck_template  1*4   1*3   1*3   00036
make_input_deck_template  1*8   1*3   1*2   00048

make_input_deck_template  1*8   1*3   1*3   00072
make_input_deck_template  2*8   1*3   1*3   00144
make_input_deck_template  2*8   2*3   1*3   00288
make_input_deck_template  2*8   2*3   2*3   00576
