#!/bin/bash

aprun -n 256 -d 1 -j 4 /usr/bin/time -p reconnection_nn_0001_nppn_256.Linux >& run_reconnection_nn_0001_nppn_256_001.log
aprun -n 128 -d 1 -j 2 /usr/bin/time -p reconnection_nn_0001_nppn_128.Linux >& run_reconnection_nn_0001_nppn_128_001.log
aprun -n  64 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_064.Linux >& run_reconnection_nn_0001_nppn_064_001.log
aprun -n  32 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_032.Linux >& run_reconnection_nn_0001_nppn_032_001.log
aprun -n  16 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_016.Linux >& run_reconnection_nn_0001_nppn_016_001.log
aprun -n   8 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_008.Linux >& run_reconnection_nn_0001_nppn_008_001.log
aprun -n   4 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_004.Linux >& run_reconnection_nn_0001_nppn_004_001.log
aprun -n   2 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_002.Linux >& run_reconnection_nn_0001_nppn_002_001.log
aprun -n   1 -d 1 -j 1 /usr/bin/time -p reconnection_nn_0001_nppn_001.Linux >& run_reconnection_nn_0001_nppn_001_001.log
