#!/bin/bash
#PBS -j oe
#PBS -N vpic_knl_mpi_and_pthreads_0512
#PBS -l walltime=2:00:00
#PBS -l nodes=512

#set -x

cd ${PBS_O_WORKDIR}

source ./bashrc.modules

module list

export MPICH_MEMORY_REPORT=3

aprun -n 32768 -N 64 -d 4 -j 4 reconnection_nn_0512_nppn_064.Linux --tpp 4 >& run_reconnection_nn_0512_nppn_064_004.log
