#!/bin/bash

export PATH=/home/wdn/Packages/openmpi/openmpi_1.10.1_gcc_511/bin:$PATH

/usr/bin/time -p mpirun -n 1 reconnection_407_np_01.op restart restart1/restart >& run_reconnection_407_np_01_1_restart.log
