#!/bin/bash

export BG_THREADLAYOUT=2

export LD_LIBRARY_PATH=/usr/gapps/artab/users/wdn/Projects/vpic_project/build/RZUSEQ_MASTER_LINUX_GNU_OPT_IBM_MPI_V4_PORT/vpic/lib/.libs:$LD_LIBRARY_PATH

/usr/bin/time -p srun -n 2 --ntasks-per-node=2 --ntasks-per-socket=2 --ntasks-per-core=1 test_Seq_case_02_np_02.powerpc64 --tpp 2 >& run_test_Seq_case_02_np_02_2.log
