#!/bin/bash

aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131,136-199,204-267 reconnection_nn_0001_nppn_001.Linux --tpp 256 >& run_reconnection_nn_0001_nppn_001_256.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63,68-131                 reconnection_nn_0001_nppn_001.Linux --tpp 128 >& run_reconnection_nn_0001_nppn_001_128.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-63                        reconnection_nn_0001_nppn_001.Linux --tpp  64 >& run_reconnection_nn_0001_nppn_001_064.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-31                        reconnection_nn_0001_nppn_001.Linux --tpp  32 >& run_reconnection_nn_0001_nppn_001_032.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-15                        reconnection_nn_0001_nppn_001.Linux --tpp  16 >& run_reconnection_nn_0001_nppn_001_016.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-7                         reconnection_nn_0001_nppn_001.Linux --tpp   8 >& run_reconnection_nn_0001_nppn_001_008.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-3                         reconnection_nn_0001_nppn_001.Linux --tpp   4 >& run_reconnection_nn_0001_nppn_001_004.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+0-1                         reconnection_nn_0001_nppn_001.Linux --tpp   2 >& run_reconnection_nn_0001_nppn_001_002.log
aprun -n 1 -d 1 -j 1 /usr/bin/time -p numactl --physcpubind=+1                           reconnection_nn_0001_nppn_001.Linux --tpp   1 >& run_reconnection_nn_0001_nppn_001_001.log
