#!/bin/bash

#######################################################################
# Documentation of problem.
#
# This is a reconnection problem from Bill Daughton which has a grid
# size of 272x144x128 and can be weak scaled in the y-direction. The
# grid dimensions contain factors of 2, 3 and 17 and thus allow doing
# strong scaling studies on Trinity Haswell and KNL and CTS1 Broadwell
# and making comparisons across these three types of nodes. This input
# deck is related to reconnection_3 but allows writing extensive file
# IO.
#
#######################################################################
# Documentation of parameters.
#
# $1 = nranks_x
# $2 = nranks_y
# $3 = nranks_z
# $4 = nranks
#
#######################################################################
# Create the input deck templates.

#------------------------------------------------
#                         $1    $2    $3    $4
#------------------------------------------------
make_input_deck_template  1*1   1*1   1*1   0000001  # MPI Domain Grid: 272 x 144 x 128
make_input_deck_template  1*2   1*1   1*1   0000002  # MPI Domain Grid: 136 x 144 x 128
make_input_deck_template  1*4   1*1   1*1   0000004  # MPI Domain Grid:  68 x 144 x 128
make_input_deck_template  1*8   1*1   1*1   0000008  # MPI Domain Grid:  34 x 144 x 128
make_input_deck_template  1*16  1*1   1*1   0000016  # MPI Domain Grid:  17 x 144 x 128
make_input_deck_template  1*17  1*1   1*1   0000017  # MPI Domain Grid:  16 x 144 x 128
make_input_deck_template  1*16  1*2   1*1   0000032  # MPI Domain Grid:  17 x  72 x 128
make_input_deck_template  1*17  1*2   1*1   0000034  # MPI Domain Grid:  16 x  72 x 128
make_input_deck_template  1*16  1*4   1*1   0000064  # MPI Domain Grid:  17 x  36 x 128
make_input_deck_template  1*17  1*4   1*1   0000068  # MPI Domain Grid:  16 x  36 x 128
make_input_deck_template  1*16  1*8   1*1   0000128  # MPI Domain Grid:  17 x  18 x 128
make_input_deck_template  1*17  1*8   1*1   0000136  # MPI Domain Grid:  16 x  18 x 128
make_input_deck_template  1*16  1*16  1*1   0000256  # MPI Domain Grid:  17 x   9 x 128
make_input_deck_template  1*17  1*16  1*1   0000272  # MPI Domain Grid:  16 x   9 x 128

make_input_deck_template  1*16  1*16  2*1   0000512  # MPI Domain Grid:  17 x   9 x  64
make_input_deck_template  1*17  1*16  2*1   0000544  # MPI Domain Grid:  16 x   9 x  64
make_input_deck_template  2*17  1*16  2*1   0001088  # MPI Domain Grid:   8 x   9 x  64
make_input_deck_template  4*17  1*16  2*1   0002176  # MPI Domain Grid:   4 x   9 x  64

make_input_deck_template  1*2   1*3   1*1   0000006  # MPI Domain Grid: 136 x  48 x 128
make_input_deck_template  1*4   1*3   1*1   0000012  # MPI Domain Grid:  68 x  48 x 128
make_input_deck_template  1*2   1*9   1*1   0000018  # MPI Domain Grid: 136 x  16 x 128
make_input_deck_template  1*8   1*3   1*1   0000024  # MPI Domain Grid:  34 x  48 x 128
make_input_deck_template  1*4   1*9   1*1   0000036  # MPI Domain Grid:  68 x  16 x 128
make_input_deck_template  1*16  1*3   1*1   0000048  # MPI Domain Grid:  17 x  48 x 128
make_input_deck_template  1*8   1*9   1*1   0000072  # MPI Domain Grid:  34 x  16 x 128

make_input_deck_template  1*8   1*9   2*1   0000144  # MPI Domain Grid:  34 x  16 x  64
make_input_deck_template  2*8   1*9   2*1   0000288  # MPI Domain Grid:  17 x  16 x  64
make_input_deck_template  2*8   2*9   2*1   0000576  # MPI Domain Grid:  17 x   8 x  64
